version: '3.8'

services:
  # Backend API Service
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb+srv://your_mongo_url
      - JWT_SECRET=secret123key
    restart: always

  # Frontend Web App Service
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always